// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Rajesh D'Monte
#include "ConsoleServer.h"
#include "Console.h"
#include "../core/Diag.h"
#include "../core/Log.h"
#include "../editor/EditorAssets.h"
#include "../editor/EditorRoutes.h"

#include <civetweb.h>
#include <nlohmann/json.hpp>

#include <algorithm>
#include <array>

#include <fmt/format.h>

// Cross-platform sockets: POSIX BSD on macOS/Linux, Winsock2 on Windows.
// Winsock headers MUST come before <windows.h> (which civetweb may pull
// in transitively), so include them first. The shim below normalises
// the type / function / errno differences so the rest of the file can
// stay readable.
#if defined(_WIN32)
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <winsock2.h>
#  include <ws2tcpip.h>
#  pragma comment(lib, "Ws2_32.lib")
#  define PT_SOCK_CLOSE   ::closesocket
#  define PT_SOCK_SHUTDOWN_BOTH SD_BOTH
#  define PT_SOCK_LASTERR ::WSAGetLastError()
#  define PT_STRCASECMP   _stricmp
   using pt_sock_t  = SOCKET;
   using pt_socklen = int;
   using pt_ssize_t = int;
   inline constexpr pt_sock_t kPtInvalidSock = INVALID_SOCKET;
   inline bool pt_sock_valid(pt_sock_t s) { return s != INVALID_SOCKET; }
#else
#  include <arpa/inet.h>
#  include <netinet/in.h>
#  include <strings.h>
#  include <sys/socket.h>
#  include <sys/types.h>
#  include <unistd.h>
#  include <cerrno>
#  define PT_SOCK_CLOSE   ::close
#  define PT_SOCK_SHUTDOWN_BOTH SHUT_RDWR
#  define PT_SOCK_LASTERR errno
#  define PT_STRCASECMP   strcasecmp
   using pt_sock_t  = int;
   using pt_socklen = socklen_t;
   using pt_ssize_t = ssize_t;
   inline constexpr pt_sock_t kPtInvalidSock = -1;
   inline bool pt_sock_valid(pt_sock_t s) { return s >= 0; }
#endif

#include <cctype>
#include <chrono>
#include <condition_variable>
#include <cstring>
#include <memory>
#include <utility>

namespace {
// Translate an errno-like int into a printable string. Winsock doesn't
// populate strerror() for socket errors -- WSAGetLastError() returns a
// numeric WSA* code that strerror() would mistranslate -- so on Windows
// we just print the number. Good enough for a log line.
inline std::string SockErrStr(int err) {
#if defined(_WIN32)
    return fmt::format("WSA error {}", err);
#else
    return std::strerror(err);
#endif
}
}  // namespace

// Embedded web UI bytes (generated by pt_embed_resource into bin blobs).
extern "C" {
extern const unsigned char web_index_html_data[];
extern const unsigned long web_index_html_size;
extern const unsigned char web_console_js_data[];
extern const unsigned long web_console_js_size;
extern const unsigned char web_console_css_data[];
extern const unsigned long web_console_css_size;
}

namespace pt::console {

namespace {

ConsoleServer* g_instance = nullptr;
using nlohmann::json;

double NowSeconds() {
    using clk = std::chrono::system_clock;
    auto d = clk::now().time_since_epoch();
    return std::chrono::duration_cast<std::chrono::duration<double>>(d).count();
}

const char* LevelName(pt::log::Level lv) {
    switch (lv) {
        case pt::log::Level::Info:  return "info";
        case pt::log::Level::Warn:  return "warn";
        case pt::log::Level::Error: return "error";
    }
    return "info";
}

// Safe string-field read for untrusted wire JSON. nlohmann's
// json::value<std::string>() calls get<std::string>() whenever the key
// EXISTS, and a type mismatch there JSON_THROWs -- but pt_console
// builds with JSON_NOEXCEPTION under -fno-exceptions, which maps
// JSON_THROW straight to std::abort(). So a single message like
// {"type":"select","id":5} (a documented legacy shape: numeric object
// id in `id`) would kill the whole engine process before the guarded
// numeric fallback could run. Every string field read in
// HandleWsMessage goes through this instead: absent key OR wrong-typed
// value yields "" -- the same result value() gives for an absent key.
std::string StrField(const json& m, const char* key) {
    auto it = m.find(key);
    return (it != m.end() && it->is_string()) ? it->get<std::string>()
                                              : std::string{};
}

void SendStaticHttp(mg_connection* conn, const char* mime,
                    const unsigned char* data, std::size_t size) {
    mg_response_header_start(conn, 200);
    mg_response_header_add(conn, "Content-Type", mime, -1);
    mg_response_header_add(conn, "Cache-Control", "no-cache", -1);
    auto len_str = std::to_string(size);
    mg_response_header_add(conn, "Content-Length", len_str.c_str(),
                           static_cast<int>(len_str.size()));
    mg_response_header_send(conn);
    mg_write(conn, data, size);
}

}  // namespace

// ============================================================================

ConsoleServer::ConsoleServer() = default;
ConsoleServer::~ConsoleServer() { Stop(); }

void ConsoleServer::SetGlobalInstance(ConsoleServer* s) { g_instance = s; }

bool ConsoleServer::Start(const Config& cfg, Console* console) {
    if (ctx_ != nullptr) return false;
    config_  = cfg;
    console_ = console;

#if defined(_WIN32)
    // Winsock requires per-process init before any socket() / bind() call.
    // civetweb does its own WSAStartup internally, but our line-protocol
    // listener is independent so we initialise here and pair with a
    // matching WSACleanup() in Stop() (or in any failure-path unwind
    // below).  Track success so a later mg_start() failure can pair
    // each init with its matching cleanup -- otherwise repeated
    // Start() retries leak process-wide socket / library state.
    bool wsa_started = false;
    {
        WSADATA wsa{};
        int wsa_err = WSAStartup(MAKEWORD(2, 2), &wsa);
        if (wsa_err != 0) {
            LOG_ERROR("WSAStartup failed: {}", wsa_err);
            // Carry on -- HTTP via civetweb may still work.
        } else {
            wsa_started = true;
        }
    }
#endif

    mg_init_library(0);
    bool mg_lib_initialised = true;

    auto port_spec = fmt::format("{}:{}", config_.bind_address, config_.http_port);
    const char* opts[] = {
        "listening_ports",      port_spec.c_str(),
        "num_threads",          "8",
        "decode_url",           "no",
        "enable_keep_alive",    "yes",
        "websocket_timeout_ms", "3600000",
        nullptr,
    };

    mg_callbacks callbacks{};
    ctx_ = mg_start(&callbacks, this, opts);
    if (ctx_ == nullptr) {
        LOG_ERROR("Failed to start civetweb on {}", port_spec);
        // Unwind in reverse init order so process-wide library state
        // doesn't leak across retried Start() calls.
        if (mg_lib_initialised) {
            mg_exit_library();
        }
#if defined(_WIN32)
        if (wsa_started) {
            WSACleanup();
        }
#endif
        return false;
    }

    // HTTP routes: serve embedded UI.
    mg_set_request_handler(ctx_, "/", &ConsoleServer::HttpHandler, this);

    // WebSocket on root path.
    mg_set_websocket_handler(ctx_, "/ws",
                             &ConsoleServer::WsConnectHandler,
                             &ConsoleServer::WsReadyHandler,
                             &ConsoleServer::WsDataHandler,
                             &ConsoleServer::WsCloseHandler,
                             this);

    // Line protocol on second port.
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port   = htons(config_.line_port);
    if (inet_pton(AF_INET, config_.bind_address.c_str(), &addr.sin_addr) <= 0) {
        addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    }

    pt_sock_t s = ::socket(AF_INET, SOCK_STREAM, 0);
    if (!pt_sock_valid(s)) {
        LOG_ERROR("line socket(): {}", SockErrStr(PT_SOCK_LASTERR));
        line_fd_ = kInvalidSocket;
        return true;  // HTTP is up; carry on without line protocol
    }
    int reuse = 1;
    setsockopt(s, SOL_SOCKET, SO_REUSEADDR,
               reinterpret_cast<const char*>(&reuse), sizeof(reuse));
    if (::bind(s, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) < 0) {
        LOG_ERROR("line bind {}:{}: {}", config_.bind_address,
                  config_.line_port, SockErrStr(PT_SOCK_LASTERR));
        PT_SOCK_CLOSE(s);
        line_fd_ = kInvalidSocket;
    } else if (::listen(s, 8) < 0) {
        LOG_ERROR("line listen: {}", SockErrStr(PT_SOCK_LASTERR));
        PT_SOCK_CLOSE(s);
        line_fd_ = kInvalidSocket;
    } else {
        line_fd_ = static_cast<socket_handle_t>(s);
        line_run_ = true;
        line_thread_ = std::thread(&ConsoleServer::LineAcceptLoop, this);
    }

    // Banner spacers stay on plain LOG_INFO so they're truly blank
    // instead of "[console] " with a trailing space. Only the content
    // lines tier-gate; per Copilot review on PR #6.
    LOG_INFO("");
    PT_DIAG_TIER1("console", "---- console listening ----");
    PT_DIAG_TIER1("console", "  Web UI    http://{}:{}/", config_.bind_address, config_.http_port);
    PT_DIAG_TIER1("console", "  WebSocket ws://{}:{}/ws",  config_.bind_address, config_.http_port);
    PT_DIAG_TIER1("console", "  Line TCP  {}:{}",           config_.bind_address, config_.line_port);
    PT_DIAG_TIER1("console", "  Auth      disabled");
    PT_DIAG_TIER1("console", "---------------------------");
    LOG_INFO("");

    return true;
}

void ConsoleServer::Stop() {
    line_run_ = false;
    if (line_fd_ != kInvalidSocket) {
        auto s = static_cast<pt_sock_t>(line_fd_);
        ::shutdown(s, PT_SOCK_SHUTDOWN_BOTH);
        PT_SOCK_CLOSE(s);
        line_fd_ = kInvalidSocket;
    }
    // Wake every per-client worker parked in a blocking recv().
    // Closing the listen socket above only unblocks the accept loop;
    // accepted client sockets are independent, so a connected-but-
    // idle client would otherwise hold its worker in recv() forever
    // and the joins below would hang engine shutdown. shutdown() --
    // not close() -- so the worker still owns the fd's lifetime and
    // closes it on loop exit as usual. Workers racing between accept
    // and set-insertion are safe too: they re-check line_run_ (now
    // false) before their first recv().
    {
        std::lock_guard lock(line_clients_mutex_);
        for (socket_handle_t cfd : line_clients_) {
            ::shutdown(static_cast<pt_sock_t>(cfd), PT_SOCK_SHUTDOWN_BOTH);
        }
    }
    if (line_thread_.joinable()) line_thread_.join();
    // Move the worker handles out under the lock, then join OUTSIDE it:
    // an exiting worker takes line_workers_mutex_ to publish itself as
    // reapable, so joining while holding it would deadlock.
    std::vector<std::thread> to_join;
    {
        std::lock_guard workers_lock(line_workers_mutex_);
        to_join.swap(line_workers_);
        line_workers_done_.clear();
    }
    for (auto& t : to_join) {
        if (t.joinable()) t.join();
    }

    if (ctx_ != nullptr) {
        mg_stop(ctx_);
        ctx_ = nullptr;
        mg_exit_library();
    }

#if defined(_WIN32)
    // Pair the WSAStartup() in Start(). Safe to call even if startup
    // failed; Winsock just returns an error which we ignore.
    WSACleanup();
#endif
}

// ----- HTTP -----------------------------------------------------------------

int ConsoleServer::HttpHandler(mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    (void)self;
    const auto* req = mg_get_request_info(conn);
    std::string_view uri = req->local_uri ? req->local_uri : "/";
    if (uri == "/" || uri == "/index.html") {
        SendStaticHttp(conn, "text/html; charset=utf-8",
                       web_index_html_data, web_index_html_size);
        return 200;
    }
    if (uri == "/console.js") {
        SendStaticHttp(conn, "application/javascript",
                       web_console_js_data, web_console_js_size);
        return 200;
    }
    if (uri == "/console.css") {
        SendStaticHttp(conn, "text/css",
                       web_console_css_data, web_console_css_size);
        return 200;
    }

    // Editor routes (React+Vite multi-panel). pt::editor::ResolveRoute
    // handles three cases internally:
    //   - `/editor`                synthesised panel index
    //   - `/editor/<panel>`        rewrites to the panel's index.html
    //   - `/panels/<...>`          direct lookup in the embedded table
    //   - `/shared/<...>`          ditto
    // A miss returns nullptr -> 404 fall-through.
    if (uri == "/editor" || uri.starts_with("/editor/") ||
        uri.starts_with("/panels/") || uri.starts_with("/shared/")) {
        if (const auto* asset = pt::editor::ResolveRoute(uri)) {
            SendStaticHttp(conn, asset->mime, asset->data, asset->size);
            return 200;
        }
    }

    mg_send_http_error(conn, 404, "%s", "not found");
    return 404;
}

// ----- WebSocket ------------------------------------------------------------

int ConsoleServer::WsConnectHandler(const mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    const auto* req = mg_get_request_info(conn);

    // Origin check: same-origin, absent (raw clients), or the Vite dev
    // servers. In dev mode (r_editor_dev_mode) the panels are served
    // from Vite on :5173 (dev) / :5174 (preview) -- see
    // web/editor/vite.config.ts (strictPort) -- but their WebSocket
    // still targets the engine's HTTP port directly (endpoint.ts), so
    // the handshake arrives with a cross-origin Origin header.
    //
    // A browser's Origin carries the host the user DIALED, never the
    // address we bound: pages served by the engine build their WS URL
    // from location.host (console.js / endpoint.ts). So the primary
    // same-origin test compares Origin against "http://" + the
    // request's own Host header -- that's what keeps non-loopback
    // binds working (net_bind_address=0.0.0.0 never appears in a real
    // Origin, and a LAN client dials the machine's LAN IP). The
    // literal spellings below back that up: both loopback names for
    // the engine port (localhost vs 127.0.0.1 are distinct origins to
    // a browser), the configured bind_address form for explicit
    // single-IP binds, and the Vite dev/preview pairs.
    if (req != nullptr) {
        const char* origin_hdr = nullptr;
        const char* host_hdr   = nullptr;
        for (int i = 0; i < req->num_headers; ++i) {
            if (PT_STRCASECMP(req->http_headers[i].name, "Origin") == 0) {
                origin_hdr = req->http_headers[i].value;
            } else if (PT_STRCASECMP(req->http_headers[i].name, "Host") == 0) {
                host_hdr = req->http_headers[i].value;
            }
        }
        if (origin_hdr != nullptr) {
            const std::string origin = origin_hdr;
            // Fixed allowlist of the host:port spellings we'll ever
            // legitimately be dialed as. Both loopback names (localhost
            // and 127.0.0.1 are distinct origins to a browser), the
            // configured bind_address for an explicit single-IP bind,
            // and the Vite dev/preview pairs.
            const std::array<std::string, 7> allowed = {
                fmt::format("http://localhost:{}", self->config_.http_port),
                fmt::format("http://127.0.0.1:{}", self->config_.http_port),
                // Inert when bind_address is 0.0.0.0 / a loopback
                // duplicate; matches when the user bound one explicit
                // LAN IP.
                fmt::format("http://{}:{}",
                    self->config_.bind_address, self->config_.http_port),
                std::string("http://localhost:5173"),
                std::string("http://localhost:5174"),
                std::string("http://127.0.0.1:5173"),
                std::string("http://127.0.0.1:5174"),
            };
            auto in_allowlist = [&](const std::string& s) {
                return std::find(allowed.begin(), allowed.end(), s)
                       != allowed.end();
            };

            // Validate the HOST header against the allowlist FIRST. The
            // same-origin fast-path below compares Origin to Host, but
            // Host is attacker-controlled -- a DNS-rebinding page
            // (evil.com rebound to 127.0.0.1) sends matching
            // Origin: http://evil.com:PORT and Host: evil.com:PORT,
            // which a bare Origin==Host test accepts, handing a
            // malicious web page full unauthenticated console/exec
            // access on a loopback-bound engine. Rejecting unknown
            // Hosts kills rebinding on both paths.
            const bool host_ok = (host_hdr != nullptr && *host_hdr != '\0')
                                 && in_allowlist(fmt::format("http://{}", host_hdr));

            bool ok = false;
            if (host_ok) {
                // Same-origin: Origin equals the (now-vetted) Host.
                ok = (origin == fmt::format("http://{}", host_hdr));
            }
            if (!ok) {
                // Cross-origin but explicitly allowed (Vite dev panels
                // dialing the engine port; a client on one loopback
                // spelling served from the other).
                ok = in_allowlist(origin);
            }
            if (!ok) {
                LOG_WARN("WS rejected: bad Origin '{}' (Host '{}')",
                         origin, host_hdr ? host_hdr : "");
                return 1;  // reject
            }
        }
    }

    std::lock_guard lock(self->ws_mutex_);
    self->ws_clients_[const_cast<mg_connection*>(conn)] = WsClient{
        const_cast<mg_connection*>(conn), {}
    };
    return 0;  // accept
}

void ConsoleServer::WsReadyHandler(mg_connection* /*conn*/, void* /*cbdata*/) {
    // Could send a hello here. For now the client subscribes itself.
}

int ConsoleServer::WsDataHandler(mg_connection* conn, int op, char* data,
                                 std::size_t len, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    (void)op;
    if ((op & 0xF) == MG_WEBSOCKET_OPCODE_CONNECTION_CLOSE) return 0;
    // Cap inbound frames. civetweb buffers the whole text frame before
    // this callback fires, and without a cap the payload would flow
    // wholesale into Console's exec queue and sit there until the next
    // Drain() -- one client could balloon memory far past anything the
    // engine budgets for. 1 MiB matches the bracket-batch cap in
    // Console::Drain(): same OOM class, same budget.
    constexpr std::size_t kMaxWsPayloadBytes = 1u * 1024u * 1024u;
    if (len > kMaxWsPayloadBytes) {
        LOG_WARN("WS message dropped: {} bytes exceeds {} byte cap",
                 len, kMaxWsPayloadBytes);
        self->SendWs(conn,
                     R"({"type":"result","ok":false,"error":"message too large"})");
        return 1;  // keep the connection; just drop the oversized frame
    }
    if (data != nullptr && len > 0) {
        self->HandleWsMessage(conn, std::string_view(data, len));
    }
    return 1;  // keep connection
}

void ConsoleServer::WsCloseHandler(const mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    std::lock_guard lock(self->ws_mutex_);
    self->ws_clients_.erase(const_cast<mg_connection*>(conn));
}

void ConsoleServer::SendWs(mg_connection* conn, std::string_view text) {
    if (conn == nullptr) return;
    mg_websocket_write(conn, MG_WEBSOCKET_OPCODE_TEXT, text.data(),
                       text.size());
}

// ----- Message dispatch -----------------------------------------------------

void ConsoleServer::HandleWsMessage(mg_connection* conn, std::string_view payload) {
    json msg = json::parse(payload, nullptr, /*allow_exceptions=*/false);
    if (msg.is_discarded() || !msg.is_object()) {
        SendWs(conn, R"({"type":"result","ok":false,"error":"bad json"})");
        return;
    }

    // All field reads below use StrField (see anon namespace above):
    // msg.value<std::string>() aborts the process on a type-mismatched
    // field in this JSON_NOEXCEPTION build, and every byte here is
    // untrusted wire input. `id` in particular is a NUMBER in the
    // legacy select protocol (see the select handler below), so it
    // must tolerate non-string values by design.
    std::string type = StrField(msg, "type");
    std::string id   = StrField(msg, "id");

    auto reply = [&](const json& body) {
        json out = body;
        out["type"] = "result";
        if (!id.empty()) out["id"] = id;
        SendWs(conn, out.dump());
    };

    if (type == "exec") {
        std::string line = StrField(msg, "line");
        Console::Get().QueueExecute(std::move(line),
            [conn, id, this](const ExecuteResult& r) {
                json body{{"ok", r.ok}};
                if (!r.output.empty()) body["output"] = r.output;
                if (!r.ok) body["error"] = r.error;
                if (!id.empty()) body["id"] = id;
                body["type"] = "result";
                std::lock_guard lock(this->ws_mutex_);
                if (this->ws_clients_.contains(conn)) SendWs(conn, body.dump());
            });
        return;
    }

    if (type == "get_cvar") {
        // Snapshot on the MAIN thread: Execute() reassigns CVar::value
        // (a std::string) there, and reading it from this civetweb
        // worker races a reallocating string. Same reason exec /
        // set_cvar route their writes through the queue.
        std::string name = StrField(msg, "name");
        Console::Get().QueueTask([conn, id, name, this]() {
            json body;
            auto* v = Console::Get().FindCVar(name);
            if (v == nullptr) {
                body = json{{"ok", false},
                            {"error", fmt::format("unknown cvar: {}", name)}};
            } else {
                json cvarObj{
                    {"name",        v->name},
                    {"value",       v->value},
                    {"default",     v->default_value},
                    {"description", v->description},
                    {"flags",       v->flags},
                };
                if (!v->allowed_values.empty()) {
                    cvarObj["allowed_values"] = v->allowed_values;
                }
                if (v->slider_max > v->slider_min) {
                    cvarObj["slider_min"]  = v->slider_min;
                    cvarObj["slider_max"]  = v->slider_max;
                    cvarObj["slider_step"] = v->slider_step;
                }
                body = json{{"ok", true}, {"cvar", cvarObj}};
            }
            body["type"] = "result";
            if (!id.empty()) body["id"] = id;
            std::lock_guard lock(this->ws_mutex_);
            if (this->ws_clients_.contains(conn)) SendWs(conn, body.dump());
        });
        return;
    }

    if (type == "set_cvar") {
        std::string name  = StrField(msg, "name");
        std::string value = StrField(msg, "value");
        // `name` is concatenated into the console line UNQUOTED, so
        // gate it to identifier characters -- every registered cvar /
        // command name is a C identifier (PT_CVAR / PT_COMMAND
        // stringize variable names). Without this, a name like
        // "x;dev_cheats 1" would smuggle a second statement past the
        // single-cvar contract of set_cvar.
        const bool name_ok = !name.empty() &&
            std::all_of(name.begin(), name.end(), [](unsigned char c) {
                return std::isalnum(c) != 0 || c == '_';
            });
        if (!name_ok) {
            reply(json{{"ok", false},
                       {"error", fmt::format("bad cvar name: {}", name)}});
            return;
        }
        // QuoteForConsole escapes '\' and '"' (the exact inverse of
        // TokenizeLine's unescape), so a value containing a literal
        // double quote can't break out of the quoting -- previously
        // `a";dev_cheats 1;"` became `r_x "a";dev_cheats 1;""` and
        // the quote-aware ';' splitter in ExecuteScript ran the
        // injected statement.
        std::string line = fmt::format("{} {}", name, QuoteForConsole(value));
        Console::Get().QueueExecute(std::move(line),
            [conn, id, this](const ExecuteResult& r) {
                json body{{"ok", r.ok}};
                if (!r.ok) body["error"] = r.error;
                if (!r.output.empty()) body["output"] = r.output;
                if (!id.empty()) body["id"] = id;
                body["type"] = "result";
                std::lock_guard lock(this->ws_mutex_);
                if (this->ws_clients_.contains(conn)) SendWs(conn, body.dump());
            });
        return;
    }

    if (type == "list_cvars") {
        // Main-thread snapshot -- see the get_cvar comment. A panel
        // polling list_cvars while another drags a slider used to copy
        // CVar::value strings out from under Execute()'s reassignment.
        std::string prefix = StrField(msg, "prefix");
        Console::Get().QueueTask([conn, id, prefix, this]() {
            json arr = json::array();
            Console::Get().EnumerateCVars(prefix, [&arr](CVar& v) {
                json entry{
                    {"name",        v.name},
                    {"value",       v.value},
                    {"default",     v.default_value},
                    {"description", v.description},
                    {"flags",       v.flags},
                };
                if (!v.allowed_values.empty()) {
                    entry["allowed_values"] = v.allowed_values;
                }
                if (v.slider_max > v.slider_min) {
                    entry["slider_min"]  = v.slider_min;
                    entry["slider_max"]  = v.slider_max;
                    entry["slider_step"] = v.slider_step;
                }
                arr.push_back(entry);
            });
            json body{{"ok", true}, {"cvars", arr}};
            body["type"] = "result";
            if (!id.empty()) body["id"] = id;
            std::lock_guard lock(this->ws_mutex_);
            if (this->ws_clients_.contains(conn)) SendWs(conn, body.dump());
        });
        return;
    }

    if (type == "list_commands") {
        // Safe to read from this worker: commands_ is populated during
        // Engine::Init registration and never mutated afterwards (no
        // command registers/unregisters at runtime), unlike CVar::value.
        std::string prefix = StrField(msg, "prefix");
        json arr = json::array();
        Console::Get().EnumerateCommands(prefix, [&arr](Command& c) {
            json entry{
                {"name",        c.name},
                {"description", c.description},
            };
            if (!c.default_args.empty()) entry["default_args"] = c.default_args;
            arr.push_back(entry);
        });
        reply(json{{"ok", true}, {"commands", arr}});
        return;
    }

    // --- Editor backend (agent-19): list_scene + select dispatch ----------
    if (type == "list_scene") {
        // Editor scene-graph snapshot. The hook returns the full JSON
        // body so the server doesn't need to depend on pt_editor /
        // pt_engine -- only the engine knows how to populate it. When
        // the hook isn't installed we reply with an empty scene so the
        // client gets a deterministic shape rather than a parse error.
        json scene_obj;
        if (scene_dump_handler_) {
            const std::string body = scene_dump_handler_();
            scene_obj = json::parse(body, nullptr, /*allow_exceptions=*/false);
            if (scene_obj.is_discarded()) scene_obj = json::object();
        } else {
            scene_obj = json::object();
        }
        reply(json{{"ok", true}, {"scene", scene_obj}});
        return;
    }
    if (type == "select") {
        // Editor selection set. {"type":"select","kind":"prim","obj_id":N}.
        // The hook owns the SelectionKind mapping (the server doesn't
        // know about the engine's enum). The selection_change broadcast
        // is fired from the engine side AFTER it applies the mutation
        // so panels / native overlays that subscribe to that topic see
        // the same payload as a click-driven selection.
        //
        // The object id is delivered in `obj_id` so it doesn't collide
        // with the optional top-level `id` field that every inbound
        // message can carry as a request-id (echoed back in `result`
        // for client-side matching -- a string in the TS WS client).
        // For backward compat with older clients that put the object
        // id in `id` as a JSON number, we fall through to that field
        // when `obj_id` isn't present.
        std::string kind = StrField(msg, "kind");
        std::uint32_t sel_id = 0;
        if (msg.contains("obj_id") && msg["obj_id"].is_number_unsigned()) {
            sel_id = msg["obj_id"].get<std::uint32_t>();
        } else if (msg.contains("id") && msg["id"].is_number_unsigned()) {
            sel_id = msg["id"].get<std::uint32_t>();
        }
        if (select_handler_) select_handler_(kind, sel_id);
        reply(json{{"ok", true}});
        return;
    }
    // --- end Editor backend ----------------------------------------------

    if (type == "subscribe" || type == "unsubscribe") {
        std::vector<std::string> topics;
        if (msg.contains("topics") && msg["topics"].is_array()) {
            for (auto& t : msg["topics"]) {
                if (t.is_string()) topics.push_back(t.get<std::string>());
            }
        }
        std::lock_guard lock(ws_mutex_);
        auto it = ws_clients_.find(conn);
        if (it != ws_clients_.end()) {
            if (type == "subscribe") {
                for (auto& t : topics) it->second.topics.insert(t);
            } else {
                for (auto& t : topics) it->second.topics.erase(t);
            }
        }
        reply(json{{"ok", true}, {"subscribed", topics}});
        return;
    }

    reply(json{{"ok", false}, {"error", fmt::format("unknown type: {}", type)}});
}

void ConsoleServer::BroadcastEvent(std::string_view topic, std::string_view data_json) {
    auto evt = fmt::format(R"({{"type":"event","topic":"{}","ts":{:.3f},"data":{}}})",
                           topic, NowSeconds(), data_json);
    std::lock_guard lock(ws_mutex_);
    for (auto& [conn, client] : ws_clients_) {
        if (client.topics.contains(std::string(topic))) {
            SendWs(conn, evt);
        }
    }
}

void ConsoleServer::OnLog(pt::log::Level level, const std::string& body) {
    if (g_instance == nullptr) return;
    // Manually escape `body` for JSON.
    std::string escaped;
    escaped.reserve(body.size() + 8);
    for (char c : body) {
        switch (c) {
            case '"':  escaped += "\\\""; break;
            case '\\': escaped += "\\\\"; break;
            case '\b': escaped += "\\b";  break;
            case '\f': escaped += "\\f";  break;
            case '\n': escaped += "\\n";  break;
            case '\r': escaped += "\\r";  break;
            case '\t': escaped += "\\t";  break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) {
                    escaped += fmt::format("\\u{:04x}",
                                           static_cast<unsigned char>(c));
                } else {
                    escaped.push_back(c);
                }
        }
    }
    auto data = fmt::format(R"({{"level":"{}","message":"{}"}})",
                            LevelName(level), escaped);
    g_instance->BroadcastEvent("log", data);
}

// ----- Line protocol --------------------------------------------------------

void ConsoleServer::LineAcceptLoop() {
    auto listen_s = static_cast<pt_sock_t>(line_fd_);
    while (line_run_) {
        sockaddr_in caddr{};
        pt_socklen clen = sizeof(caddr);
        pt_sock_t cfd = ::accept(listen_s,
                                 reinterpret_cast<sockaddr*>(&caddr), &clen);
        if (!pt_sock_valid(cfd)) {
            if (!line_run_) break;
            continue;
        }
        // Reap workers that finished since the last accept -- otherwise
        // each short-lived `nc` connection leaves a joinable
        // std::thread (stack mapping + kernel object) parked until
        // Stop(). Extract under the lock, join after releasing it (the
        // exiting worker needs the same mutex to publish itself).
        std::vector<std::thread> finished;
        {
            std::lock_guard lock(line_workers_mutex_);
            for (auto it = line_workers_.begin(); it != line_workers_.end();) {
                auto done = std::find(line_workers_done_.begin(),
                                      line_workers_done_.end(),
                                      it->get_id());
                if (done != line_workers_done_.end()) {
                    finished.push_back(std::move(*it));
                    line_workers_done_.erase(done);
                    it = line_workers_.erase(it);
                } else {
                    ++it;
                }
            }
            line_workers_.emplace_back(&ConsoleServer::LineClientLoop, this,
                                       static_cast<socket_handle_t>(cfd));
        }
        for (auto& t : finished) {
            if (t.joinable()) t.join();
        }
    }
}

void ConsoleServer::LineClientLoop(socket_handle_t fd_) {
    auto fd = static_cast<pt_sock_t>(fd_);
    // Register with the live-client set so Stop() can ::shutdown() this
    // socket and break us out of the blocking recv() below -- closing
    // the LISTEN socket alone doesn't wake accepted clients, and the
    // join in Stop() would otherwise hang on an idle connection.
    {
        std::lock_guard lock(line_clients_mutex_);
        line_clients_.insert(fd_);
    }
    std::string buf;
    buf.reserve(256);
    char chunk[256];
    while (line_run_) {
        // Winsock recv() takes int for length and returns int; POSIX uses
        // size_t / ssize_t. Cast through pt_ssize_t to keep both compilers
        // happy without -Wnarrowing complaints.
        pt_ssize_t n = ::recv(fd, chunk,
                              static_cast<int>(sizeof(chunk)), 0);
        if (n <= 0) break;
        buf.append(chunk, chunk + n);

        std::size_t start = 0;
        for (std::size_t i = 0; i < buf.size(); ++i) {
            if (buf[i] == '\n') {
                auto line = buf.substr(start, i - start);
                if (!line.empty() && line.back() == '\r') line.pop_back();
                start = i + 1;
                if (line.empty()) continue;

                // Synchronously execute on the main-thread queue and
                // reply. The rendezvous state is heap-shared with the
                // responder: Console::Drain() may run long AFTER the
                // 2 s wait below gives up (cold pipeline builds and
                // heavy scene loads block the main thread for far
                // longer), and the queued responder fires whenever
                // Drain finally gets to it. Capturing stack locals by
                // reference here would have that late call writing
                // through dangling pointers -- a destroyed mutex and
                // ExecuteResult, or a torn-down thread stack if the
                // client disconnected. The shared_ptr keeps the state
                // alive for however late the responder fires; a
                // timed-out client simply never sees the reply.
                struct SyncState {
                    std::mutex              m;
                    std::condition_variable cv;
                    bool                    done = false;
                    ExecuteResult           result;
                };
                auto st = std::make_shared<SyncState>();
                Console::Get().QueueExecute(line,
                    [st](const ExecuteResult& r) {
                        std::lock_guard lock(st->m);
                        st->result = r;
                        st->done = true;
                        st->cv.notify_one();
                    });
                bool done = false;
                ExecuteResult result;
                {
                    std::unique_lock lock(st->m);
                    st->cv.wait_for(lock, std::chrono::seconds(2),
                                    [&]{ return st->done; });
                    done = st->done;
                    if (done) result = st->result;
                }
                if (done) {
                    if (result.ok) {
                        if (!result.output.empty()) {
                            ::send(fd, result.output.data(),
                                   static_cast<int>(result.output.size()), 0);
                            if (result.output.back() != '\n') {
                                ::send(fd, "\n", 1, 0);
                            }
                        }
                    } else {
                        std::string msg = "error: " + result.error + "\n";
                        ::send(fd, msg.data(),
                               static_cast<int>(msg.size()), 0);
                    }
                }
            }
        }
        if (start > 0) buf.erase(0, start);

        // Per-line cap on the residual (no '\n' seen yet). A client
        // that streams bytes without ever sending a newline would
        // otherwise grow `buf` until allocation failure kills the
        // process -- the same OOM class the bracket-batch path in
        // Console::Drain() caps at 1 MiB, but one transport layer
        // below it. 64 KiB dwarfs any sane console line (the largest
        // replay scripts in this codebase are batched line-by-line),
        // so tripping it means a broken or hostile client: tell it
        // why, then drop the connection.
        constexpr std::size_t kMaxLineBytes = 64u * 1024u;
        if (buf.size() > kMaxLineBytes) {
            LOG_WARN("line client dropped: unterminated line exceeds "
                     "{} byte cap", kMaxLineBytes);
            const char err[] = "error: line too long\n";
            ::send(fd, err, static_cast<int>(sizeof(err) - 1), 0);
            break;
        }
    }
    {
        std::lock_guard lock(line_clients_mutex_);
        line_clients_.erase(fd_);
    }
    PT_SOCK_CLOSE(fd);
    {
        // Publish self as reapable; the next accept (or Stop) joins us.
        std::lock_guard lock(line_workers_mutex_);
        line_workers_done_.push_back(std::this_thread::get_id());
    }
}

}  // namespace pt::console
