#include "ConsoleServer.h"
#include "Console.h"
#include "../core/Log.h"

#include <civetweb.h>
#include <nlohmann/json.hpp>

#include <fmt/format.h>

#include <arpa/inet.h>
#include <netinet/in.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#include <chrono>
#include <cstring>
#include <utility>

// Embedded web UI bytes (generated by pt_embed_resource into bin blobs).
extern "C" {
extern const unsigned char web_index_html_data[];
extern const unsigned long web_index_html_size;
extern const unsigned char web_console_js_data[];
extern const unsigned long web_console_js_size;
extern const unsigned char web_console_css_data[];
extern const unsigned long web_console_css_size;
}

namespace pt::console {

namespace {

ConsoleServer* g_instance = nullptr;
using nlohmann::json;

double NowSeconds() {
    using clk = std::chrono::system_clock;
    auto d = clk::now().time_since_epoch();
    return std::chrono::duration_cast<std::chrono::duration<double>>(d).count();
}

const char* LevelName(pt::log::Level lv) {
    switch (lv) {
        case pt::log::Level::Info:  return "info";
        case pt::log::Level::Warn:  return "warn";
        case pt::log::Level::Error: return "error";
    }
    return "info";
}

void SendStaticHttp(mg_connection* conn, const char* mime,
                    const unsigned char* data, std::size_t size) {
    mg_response_header_start(conn, 200);
    mg_response_header_add(conn, "Content-Type", mime, -1);
    mg_response_header_add(conn, "Cache-Control", "no-cache", -1);
    auto len_str = std::to_string(size);
    mg_response_header_add(conn, "Content-Length", len_str.c_str(),
                           static_cast<int>(len_str.size()));
    mg_response_header_send(conn);
    mg_write(conn, data, size);
}

}  // namespace

// ============================================================================

ConsoleServer::ConsoleServer() = default;
ConsoleServer::~ConsoleServer() { Stop(); }

void ConsoleServer::SetGlobalInstance(ConsoleServer* s) { g_instance = s; }

bool ConsoleServer::Start(const Config& cfg, Console* console) {
    if (ctx_ != nullptr) return false;
    config_  = cfg;
    console_ = console;

    mg_init_library(0);

    auto port_spec = fmt::format("{}:{}", config_.bind_address, config_.http_port);
    const char* opts[] = {
        "listening_ports",      port_spec.c_str(),
        "num_threads",          "8",
        "decode_url",           "no",
        "enable_keep_alive",    "yes",
        "websocket_timeout_ms", "3600000",
        nullptr,
    };

    mg_callbacks callbacks{};
    ctx_ = mg_start(&callbacks, this, opts);
    if (ctx_ == nullptr) {
        LOG_ERROR("Failed to start civetweb on {}", port_spec);
        return false;
    }

    // HTTP routes: serve embedded UI.
    mg_set_request_handler(ctx_, "/", &ConsoleServer::HttpHandler, this);

    // WebSocket on root path.
    mg_set_websocket_handler(ctx_, "/ws",
                             &ConsoleServer::WsConnectHandler,
                             &ConsoleServer::WsReadyHandler,
                             &ConsoleServer::WsDataHandler,
                             &ConsoleServer::WsCloseHandler,
                             this);

    // Line protocol on second port.
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port   = htons(config_.line_port);
    if (inet_pton(AF_INET, config_.bind_address.c_str(), &addr.sin_addr) <= 0) {
        addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    }

    line_fd_ = ::socket(AF_INET, SOCK_STREAM, 0);
    if (line_fd_ < 0) {
        LOG_ERROR("line socket(): {}", std::strerror(errno));
        return true;  // HTTP is up; carry on without line protocol
    }
    int reuse = 1;
    setsockopt(line_fd_, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
    if (::bind(line_fd_, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) < 0) {
        LOG_ERROR("line bind {}:{}: {}", config_.bind_address,
                  config_.line_port, std::strerror(errno));
        ::close(line_fd_);
        line_fd_ = -1;
    } else if (::listen(line_fd_, 8) < 0) {
        LOG_ERROR("line listen: {}", std::strerror(errno));
        ::close(line_fd_);
        line_fd_ = -1;
    } else {
        line_run_ = true;
        line_thread_ = std::thread(&ConsoleServer::LineAcceptLoop, this);
    }

    LOG_INFO("");
    LOG_INFO("---- console listening ----");
    LOG_INFO("  Web UI    http://{}:{}/", config_.bind_address, config_.http_port);
    LOG_INFO("  WebSocket ws://{}:{}/ws",  config_.bind_address, config_.http_port);
    LOG_INFO("  Line TCP  {}:{}",           config_.bind_address, config_.line_port);
    LOG_INFO("  Auth      disabled");
    LOG_INFO("---------------------------");
    LOG_INFO("");

    return true;
}

void ConsoleServer::Stop() {
    line_run_ = false;
    if (line_fd_ >= 0) {
        ::shutdown(line_fd_, SHUT_RDWR);
        ::close(line_fd_);
        line_fd_ = -1;
    }
    if (line_thread_.joinable()) line_thread_.join();
    for (auto& t : line_workers_) {
        if (t.joinable()) t.join();
    }
    line_workers_.clear();

    if (ctx_ != nullptr) {
        mg_stop(ctx_);
        ctx_ = nullptr;
        mg_exit_library();
    }
}

// ----- HTTP -----------------------------------------------------------------

int ConsoleServer::HttpHandler(mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    (void)self;
    const auto* req = mg_get_request_info(conn);
    std::string_view uri = req->local_uri ? req->local_uri : "/";
    if (uri == "/" || uri == "/index.html") {
        SendStaticHttp(conn, "text/html; charset=utf-8",
                       web_index_html_data, web_index_html_size);
        return 200;
    }
    if (uri == "/console.js") {
        SendStaticHttp(conn, "application/javascript",
                       web_console_js_data, web_console_js_size);
        return 200;
    }
    if (uri == "/console.css") {
        SendStaticHttp(conn, "text/css",
                       web_console_css_data, web_console_css_size);
        return 200;
    }
    mg_send_http_error(conn, 404, "%s", "not found");
    return 404;
}

// ----- WebSocket ------------------------------------------------------------

int ConsoleServer::WsConnectHandler(const mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    const auto* req = mg_get_request_info(conn);

    // Origin check: same-origin or absent (raw clients).
    if (req != nullptr) {
        for (int i = 0; i < req->num_headers; ++i) {
            if (strcasecmp(req->http_headers[i].name, "Origin") == 0) {
                std::string origin = req->http_headers[i].value
                                     ? req->http_headers[i].value : "";
                std::string ok1 = fmt::format("http://{}:{}",
                    self->config_.bind_address, self->config_.http_port);
                std::string ok2 = fmt::format("http://localhost:{}",
                    self->config_.http_port);
                if (origin != ok1 && origin != ok2) {
                    LOG_WARN("WS rejected: bad Origin '{}'", origin);
                    return 1;  // reject
                }
                break;
            }
        }
    }

    std::lock_guard lock(self->ws_mutex_);
    self->ws_clients_[const_cast<mg_connection*>(conn)] = WsClient{
        const_cast<mg_connection*>(conn), {}
    };
    return 0;  // accept
}

void ConsoleServer::WsReadyHandler(mg_connection* /*conn*/, void* /*cbdata*/) {
    // Could send a hello here. For now the client subscribes itself.
}

int ConsoleServer::WsDataHandler(mg_connection* conn, int op, char* data,
                                 std::size_t len, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    (void)op;
    if ((op & 0xF) == MG_WEBSOCKET_OPCODE_CONNECTION_CLOSE) return 0;
    if (data != nullptr && len > 0) {
        self->HandleWsMessage(conn, std::string_view(data, len));
    }
    return 1;  // keep connection
}

void ConsoleServer::WsCloseHandler(const mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    std::lock_guard lock(self->ws_mutex_);
    self->ws_clients_.erase(const_cast<mg_connection*>(conn));
}

void ConsoleServer::SendWs(mg_connection* conn, std::string_view text) {
    if (conn == nullptr) return;
    mg_websocket_write(conn, MG_WEBSOCKET_OPCODE_TEXT, text.data(),
                       text.size());
}

// ----- Message dispatch -----------------------------------------------------

void ConsoleServer::HandleWsMessage(mg_connection* conn, std::string_view payload) {
    json msg = json::parse(payload, nullptr, /*allow_exceptions=*/false);
    if (msg.is_discarded() || !msg.is_object()) {
        SendWs(conn, R"({"type":"result","ok":false,"error":"bad json"})");
        return;
    }

    std::string type = msg.value("type", std::string{});
    std::string id   = msg.value("id",   std::string{});

    auto reply = [&](const json& body) {
        json out = body;
        out["type"] = "result";
        if (!id.empty()) out["id"] = id;
        SendWs(conn, out.dump());
    };

    if (type == "exec") {
        std::string line = msg.value("line", std::string{});
        Console::Get().QueueExecute(std::move(line),
            [conn, id, this](const ExecuteResult& r) {
                json body{{"ok", r.ok}};
                if (!r.output.empty()) body["output"] = r.output;
                if (!r.ok) body["error"] = r.error;
                if (!id.empty()) body["id"] = id;
                body["type"] = "result";
                std::lock_guard lock(this->ws_mutex_);
                if (this->ws_clients_.contains(conn)) SendWs(conn, body.dump());
            });
        return;
    }

    if (type == "get_cvar") {
        std::string name = msg.value("name", std::string{});
        auto* v = Console::Get().FindCVar(name);
        if (v == nullptr) {
            reply(json{{"ok", false},
                       {"error", fmt::format("unknown cvar: {}", name)}});
            return;
        }
        reply(json{{"ok", true},
                   {"cvar", json{
                       {"name",        v->name},
                       {"value",       v->value},
                       {"default",     v->default_value},
                       {"description", v->description},
                       {"flags",       v->flags},
                   }}});
        return;
    }

    if (type == "set_cvar") {
        std::string name  = msg.value("name",  std::string{});
        std::string value = msg.value("value", std::string{});
        std::string line  = fmt::format("{} \"{}\"", name, value);
        Console::Get().QueueExecute(std::move(line),
            [conn, id, this](const ExecuteResult& r) {
                json body{{"ok", r.ok}};
                if (!r.ok) body["error"] = r.error;
                if (!r.output.empty()) body["output"] = r.output;
                if (!id.empty()) body["id"] = id;
                body["type"] = "result";
                std::lock_guard lock(this->ws_mutex_);
                if (this->ws_clients_.contains(conn)) SendWs(conn, body.dump());
            });
        return;
    }

    if (type == "list_cvars") {
        std::string prefix = msg.value("prefix", std::string{});
        json arr = json::array();
        Console::Get().EnumerateCVars(prefix, [&arr](CVar& v) {
            arr.push_back(json{
                {"name",        v.name},
                {"value",       v.value},
                {"default",     v.default_value},
                {"description", v.description},
                {"flags",       v.flags},
            });
        });
        reply(json{{"ok", true}, {"cvars", arr}});
        return;
    }

    if (type == "list_commands") {
        std::string prefix = msg.value("prefix", std::string{});
        json arr = json::array();
        Console::Get().EnumerateCommands(prefix, [&arr](Command& c) {
            arr.push_back(json{
                {"name",        c.name},
                {"description", c.description},
            });
        });
        reply(json{{"ok", true}, {"commands", arr}});
        return;
    }

    if (type == "subscribe" || type == "unsubscribe") {
        std::vector<std::string> topics;
        if (msg.contains("topics") && msg["topics"].is_array()) {
            for (auto& t : msg["topics"]) {
                if (t.is_string()) topics.push_back(t.get<std::string>());
            }
        }
        std::lock_guard lock(ws_mutex_);
        auto it = ws_clients_.find(conn);
        if (it != ws_clients_.end()) {
            if (type == "subscribe") {
                for (auto& t : topics) it->second.topics.insert(t);
            } else {
                for (auto& t : topics) it->second.topics.erase(t);
            }
        }
        reply(json{{"ok", true}, {"subscribed", topics}});
        return;
    }

    reply(json{{"ok", false}, {"error", fmt::format("unknown type: {}", type)}});
}

void ConsoleServer::BroadcastEvent(std::string_view topic, std::string_view data_json) {
    auto evt = fmt::format(R"({{"type":"event","topic":"{}","ts":{:.3f},"data":{}}})",
                           topic, NowSeconds(), data_json);
    std::lock_guard lock(ws_mutex_);
    for (auto& [conn, client] : ws_clients_) {
        if (client.topics.contains(std::string(topic))) {
            SendWs(conn, evt);
        }
    }
}

void ConsoleServer::OnLog(pt::log::Level level, const std::string& body) {
    if (g_instance == nullptr) return;
    // Manually escape `body` for JSON.
    std::string escaped;
    escaped.reserve(body.size() + 8);
    for (char c : body) {
        switch (c) {
            case '"':  escaped += "\\\""; break;
            case '\\': escaped += "\\\\"; break;
            case '\b': escaped += "\\b";  break;
            case '\f': escaped += "\\f";  break;
            case '\n': escaped += "\\n";  break;
            case '\r': escaped += "\\r";  break;
            case '\t': escaped += "\\t";  break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) {
                    escaped += fmt::format("\\u{:04x}",
                                           static_cast<unsigned char>(c));
                } else {
                    escaped.push_back(c);
                }
        }
    }
    auto data = fmt::format(R"({{"level":"{}","message":"{}"}})",
                            LevelName(level), escaped);
    g_instance->BroadcastEvent("log", data);
}

// ----- Line protocol --------------------------------------------------------

void ConsoleServer::LineAcceptLoop() {
    while (line_run_) {
        sockaddr_in caddr{};
        socklen_t clen = sizeof(caddr);
        int cfd = ::accept(line_fd_, reinterpret_cast<sockaddr*>(&caddr), &clen);
        if (cfd < 0) {
            if (!line_run_) break;
            continue;
        }
        line_workers_.emplace_back(&ConsoleServer::LineClientLoop, this, cfd);
    }
}

void ConsoleServer::LineClientLoop(int fd) {
    std::string buf;
    buf.reserve(256);
    char chunk[256];
    while (line_run_) {
        ssize_t n = ::recv(fd, chunk, sizeof(chunk), 0);
        if (n <= 0) break;
        buf.append(chunk, chunk + n);

        std::size_t start = 0;
        for (std::size_t i = 0; i < buf.size(); ++i) {
            if (buf[i] == '\n') {
                auto line = buf.substr(start, i - start);
                if (!line.empty() && line.back() == '\r') line.pop_back();
                start = i + 1;
                if (line.empty()) continue;

                // Synchronously execute on the main-thread queue and reply.
                std::mutex m;
                std::condition_variable cv;
                bool done = false;
                ExecuteResult result;
                Console::Get().QueueExecute(line,
                    [&](const ExecuteResult& r) {
                        std::lock_guard lock(m);
                        result = r;
                        done = true;
                        cv.notify_one();
                    });
                {
                    std::unique_lock lock(m);
                    cv.wait_for(lock, std::chrono::seconds(2),
                                [&]{ return done; });
                }
                if (done) {
                    if (result.ok) {
                        if (!result.output.empty()) {
                            ::send(fd, result.output.data(),
                                   result.output.size(), 0);
                            if (result.output.back() != '\n') {
                                ::send(fd, "\n", 1, 0);
                            }
                        }
                    } else {
                        std::string msg = "error: " + result.error + "\n";
                        ::send(fd, msg.data(), msg.size(), 0);
                    }
                }
            }
        }
        if (start > 0) buf.erase(0, start);
    }
    ::close(fd);
}

}  // namespace pt::console
